name: Build and Push tw-dl-runner

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/tw-dl-runner:latest
          docker build -f docker/Dockerfile -t "${IMAGE}" ./docker
          docker push "${IMAGE}"
