name: DownloaderAction
on:
  repository_dispatch:
    types:
      - download

jobs:
  run-with-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tw-dl-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Masking Secrets
        run: bash .github/scripts/run.sh mask
      - name: Start Steps
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh start
      - name: Setup latest yt-dlp
        if: ${{ success() }}
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh setup
      - name: Install scripts
        if: ${{ success() }}
        run: bash .github/scripts/run.sh install
      - name: Confirmation of link survival
        if: ${{ success() }}
        id: link_status
        timeout-minutes: 10
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh check-link
      - name: Start Download
        if: ${{ success() }}
        id: download
        timeout-minutes: 10
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          TWITTER_COOKIES: ${{ secrets.TWITTER_COOKIES }}
        run: bash .github/scripts/run.sh download
      - name: Check and Convert Files
        if: ${{ success() }}
        uses: ./.github/actions/check-and-convert-files
        with:
          endpoint_url: ${{ secrets.ENDPOINT_URL }}
          run_number: ${{ github.run_number }}
          start_time: ${{ github.event.client_payload.startTime }}
          channel: ${{ github.event.client_payload.channel }}
          message: ${{ github.event.client_payload.message }}
          token: ${{ github.event.client_payload.token }}
          link: ${{ github.event.client_payload.link }}
      - name: Upload files
        if: ${{ success() }}
        id: upload
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh upload
      - name: Link has expired
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status == 'notfound' &&
            steps.download.outputs.status == '' &&
            steps.upload.outputs.status == ''
          }}
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh failure expired
      - name: Video file not found
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status == '' &&
            steps.download.outputs.status == 'notvideo' &&
            steps.upload.outputs.status == ''
          }}
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh failure notvideo
      - name: Uploaded file size exceeded
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status == '' &&
            steps.download.outputs.status == '' &&
            steps.upload.outputs.status == 'sizeover'
          }}
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh failure sizeover
      - name: Download timed out
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status == '' &&
            steps.download.outputs.status == '' &&
            steps.upload.outputs.status == ''
          }}
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: bash .github/scripts/run.sh failure timeout
      - name: Cleanup temp files
        if: ${{ always() && !cancelled() }}
        run: bash .github/scripts/run.sh cleanup
